image: thubo/latexmk:medium

variables:
  DIR: .
  FILENAME: main

stages:
  - compile
  - publish

latexmk:
  stage: compile
  script: cd $DIR && latexmk -pdf $FILENAME.tex
  artifacts:
    paths:
      - $DIR/$FILENAME.pdf

pages:
  stage: publish
  script: mkdir public && cp $DIR/$FILENAME.pdf public/main.pdf && echo '<a href="main.pdf" target="_blank">PDF.</a>' > public/index.html
  artifacts:
    paths:
      - public
